#!/usr/bin/env python
#
#

import sys, re

def split_on_uppercase(word):
    return " ".join( [x for x in re.split(r"([A-Z][^A-Z]+)", word) if x != '' ] )

def insert_spaces(word):
    return split_on_uppercase(word)

words = sys.argv[1:]

for word in iter(words):
  print(insert_spaces(word))

# Specs:
# SpaceHereHere
# SpaceHHereHHere
